'use strict';

/**
 * application router
 */

module.exports = {
  routes: [
    // Create application
    {
      method: 'POST',
      path: '/applications',
      handler: 'application.create',
      config: {
        policies: [],
        middlewares: [],
      },
    },
    // Get my applications
    {
      method: 'GET',
      path: '/applications/me',
      handler: 'application.myApplications',
      config: {
        policies: [],
        middlewares: [],
      },
    },
    // Default routes generated by Strapi
    {
      method: 'GET',
      path: '/applications',
      handler: 'application.find',
      config: {
        policies: [],
        middlewares: [],
      },
    },
    {
      method: 'GET',
      path: '/applications/:id',
      handler: 'application.findOne',
      config: {
        policies: [],
        middlewares: [],
      },
    },
    {
      method: 'PUT',
      path: '/applications/:id',
      handler: 'application.update',
      config: {
        policies: [],
        middlewares: [],
      },
    },
    {
      method: 'DELETE',
      path: '/applications/:id',
      handler: 'application.delete',
      config: {
        policies: [],
        middlewares: [],
      },
    },
  ],
};